version: '3'

services:
  postgres:
    image: postgres:17
    container_name: postgres-container
    restart: unless-stopped
    ports:
      - "5555:5432"
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - postgres_17_data:/var/lib/postgresql/data

  redis:
    image: redis
    container_name: redis-container
    restart: unless-stopped
    ports:
      - "6379:6379"

  app:
    build: .
    restart: unless-stopped
    container_name: nodejs-app-container
    depends_on:
      - postgres
      - redis
    ports:
      - "3000:3000"
    volumes:
      - .:/app
volumes:
  postgres_17_data: